name: My Twitter Followers

on: 
  workflow_dispatch:

env:
  twitter_consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
  twitter_consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Run Python Script
        run: |
          python -m pip install requests
          python get_tweets.py
